### ISSUE TITLE
anki模板问题

### ISSUE THREAD

**Issue by kawayixixing** [itboone/anki-template#2]
开发大大最近再用你开发的anki模板，批量导入题库很爽。谢谢您。

问一下模板能不能升级一下。因为每次答题都要选择显示答案，比较麻烦。希望在选择题（单选、多选）上加入自动判断选项是否正确，而可以更快更方便的刷题。

之前在用的模板是这个[anki模板](https://zhangsn.me/anki-ultimate-template/)
它实现的功能就是选择选项直接判断对错，而无需再点击显示答案，这样方便快捷。

谢谢开发大大看到这里，如果您还继续有兴趣改进该模板的话，希望这点提议对您有用。如果可以的话，我愿意赞助硬币给您用于继续改进该模板。

**Comment by zhumingyu** [comment]
@kawayixixing 朋友你的这个问题解决了没？

**Comment by itboone** [comment]
@kawayixixing 你这个我建议你花钱买人家模板用就行了，你可以查一查各大软件公司开发岗时薪都是多少。就做你说的这些升级连开发带测试，少说也得半天时间。而且我个人精力有限没时间做这些东西，网上那些免费开源的模板且用且珍惜！
